version: '3.0'

services:
  sqlserver:
    environment:
      - SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  migrations:
    image: 'microservice-demo/migrations:${TAG:-latest}'
    build:
      context: ../..
      dockerfile: samples/MicroserviceDemo/databases/Dockerfile
    depends_on:
      - sqlserver
