apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: auth-server
  name: auth-server
spec:
  ports:
  - port: 51511
    targetPort: 51511
  selector:
    io.kompose.service: auth-server
status:
  loadBalancer: {}
