apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: backend-admin-app-gateway
  name: backend-admin-app-gateway
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    io.kompose.service: backend-admin-app-gateway
status:
  loadBalancer: {}
