apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend-admin-app
  name: backend-admin-app
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: backend-admin-app
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: AuthServer__Authority
          value: http://auth-server:51511
        - name: Redis__Configuration
          value: redis
        - name: RemoteServices__Default__BaseUrl
          value: http://backend-admin-app-gateway/
        image: volosoft/microservice-demo-backend-admin-app
        name: backend-admin-app
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
