apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: blogging-service
  name: blogging-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    io.kompose.service: blogging-service
status:
  loadBalancer: {}
