apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: auth-server
  name: auth-server-expose
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: auth-server
  ports:
    - protocol: TCP
      port: 51511
      targetPort: 51511
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: backend-admin-app
  name: backend-admin-app-expose
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: backend-admin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: public-website
  name: public-website-expose
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: public-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003