apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    io.kompose.service: product-service
status:
  loadBalancer: {}
