apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: public-website
  name: public-website
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    io.kompose.service: public-website
status:
  loadBalancer: {}
