apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: sqlserver
  name: sqlserver
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    io.kompose.service: sqlserver
status:
  loadBalancer: {}
