name: "Angular build and test action"
on:
  pull_request:
    paths:
    - 'npm/ng-packs/**'
  push:
    paths:
    - 'npm/ng-packs/**'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: pwd && npm install
        working-directory: npm/ng-packs
      - run: pwd
