name: "Angular build and test"
on:
  pull_request:
    paths:
      - 'npm/ng-packs/**'
    branches:
      - master
      - dev
  push:
    paths:
      - 'npm/ng-packs/**'
    branches:
      - master
      - dev
jobs:
  install_build_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: nuxt/actions-yarn@node-10
      - run: |
          node -v
          yarn
          yarn symlink copy --angular --packages @abp/ng.core --sync-build --no-watch
        working-directory: npm/ng-packs
