name: "Angular build and test action"
on:
  pull_request:
    paths:
      - 'npm/ng-packs/**'
    branches:
      - master
      - dev
  push:
    paths:
      - 'npm/ng-packs/**'
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: pwd
