name: "Angular build and test action"
on:
  pull_request:
    paths:
    - 'npm/ng-packs/**'
  push:
    paths:
    - 'npm/ng-packs/**'
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          node-version: '10.x'
      - run: | 
          pwd
          yarn
      - run: pwd
